// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJOQ__Bu3vkkrYaztgE3-9n62e6WBFlCE',
    appId: '1:639802461548:web:1103c5a3ca4368ded07749',
    messagingSenderId: '639802461548',
    projectId: 'mamitas-glam',
    authDomain: 'mamitas-glam.firebaseapp.com',
    storageBucket: 'mamitas-glam.appspot.com',
    measurementId: 'G-CBJC3187BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATCWJUWYFussKLZTq-JSnVskguOYux09o',
    appId: '1:639802461548:android:9bf94f52d2debf26d07749',
    messagingSenderId: '639802461548',
    projectId: 'mamitas-glam',
    storageBucket: 'mamitas-glam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADjDOsWr068T5xnzigH2ZbMmusGWUFhXg',
    appId: '1:639802461548:ios:8b200a43b5f4a7c8d07749',
    messagingSenderId: '639802461548',
    projectId: 'mamitas-glam',
    storageBucket: 'mamitas-glam.appspot.com',
    iosClientId: '639802461548-tqjeq1aea3nlb13g999ugihic431lpbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADjDOsWr068T5xnzigH2ZbMmusGWUFhXg',
    appId: '1:639802461548:ios:8b200a43b5f4a7c8d07749',
    messagingSenderId: '639802461548',
    projectId: 'mamitas-glam',
    storageBucket: 'mamitas-glam.appspot.com',
    iosClientId: '639802461548-tqjeq1aea3nlb13g999ugihic431lpbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
